# 1 "temp/res/MMSApp.c"
# 1 "<built-in>"
# 1 "<command line>"
# 1 "temp/res/MMSApp.c"
# 1 "../../mmi/inc/mmi_features.h" 1
# 69 "../../mmi/inc/mmi_features.h"
# 1 "../../mmi/inc/MMI_features_switch.h" 1
# 67 "../../mmi/inc/MMI_features_switch.h"
# 1 "../../mmi/inc/MMI_features_type.h" 1
# 68 "../../mmi/inc/MMI_features_switch.h" 2
# 70 "../../mmi/inc/mmi_features.h" 2
# 2 "temp/res/MMSApp.c" 2
# 1 "../customerinc/CustResDef.h" 1
# 195 "../customerinc/CustResDef.h"
# 1 "../../mmi/inc/MMI_features.h" 1
# 196 "../customerinc/CustResDef.h" 2
# 3 "temp/res/MMSApp.c" 2
<?xml version="1.0" encoding="UTF-8"?>






<APP id="APP_UMMS_MMS">



    <!--Include Area-->
    <INCLUDE file="GlobalResDef.h,GlobalMenuItems.h,MessagesResDef.h" />
    <INCLUDE file="mmi_rp_app_unifiedmessage_def.h" />







    <!-----------------------------------------------------String Resource Area----------------------------------------------------->
# 59 "temp/res/MMSApp.c"
        <STRING id="STR_ID_UMMS_BGSR_RESULT_SEND_FAIL"/>
        <STRING id="STR_ID_UMMS_BGSR_RESULT_DOWNLOAD_FAIL"/>

        <STRING id="STR_ID_UMMS_BGSR_RESULT_FAIL_COMM_CONNECT_ERROR"/>
# 73 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_BYTES"/>

    <STRING id="STR_ID_UMMS_BYTE"/>

    <STRING id="STR_ID_UMMS_KB"/>
    <STRING id="STR_ID_UMMS_MMS_SETTINGS"/>


    <STRING id="STR_ID_UMMS_DELIVERY_REPORT"/>


        <STRING id="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT"/>
# 93 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM"/>




    <STRING id="STR_ID_UMMS_MESSAGE_SETTINGS_COMMON_SETTINGS"/>


    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE"/>




    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <STRING id="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>
    <STRING id="STR_ID_UMMS_MMS_NO_MEM_CARD"/>
# 132 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_MESSAGE_IS_IN_SEND"/>

    <STRING id="STR_ID_UMMS_READ_REPORT_IS_IN_SEND"/>

    <STRING id="STR_ID_UMMS_SETTINGS_FREE_SPACE"/>
# 155 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_MODE_WARNING_CONFIRM"/>
    <STRING id="STR_ID_UMMS_SETTINGS_SIGNATURE_AUDIO"/>
    <STRING id="STR_ID_UMMS_RESTRICTED_MODE"/>
# 203 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_SETTINGS_READ_REPORT"/>

        <STRING id="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT"/>
        <STRING id="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT"/>



    <STRING id="STR_ID_UMMS_SETTINGS_IMMEDIATE"/>
# 222 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE"/>
# 233 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_SETTINGS_HOME_NETWORK"/>







    <STRING id="STR_ID_UMMS_SETTINGS_ON_REQUEST"/>

    <STRING id="STR_ID_UMMS_RESEND"/>

    <STRING id="STR_ID_UMMS_SETTINGS_NEVER_SEND"/>
# 265 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_TOTAL"/>
    <STRING id="STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_USAGE"/>






    <STRING id="STR_ID_UMMS_URL_TOO_LONG" />
# 284 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_CORRUPT_DRM_MEDIA" />

    <STRING id="STR_ID_UMMS_USE_DETAILS_SENDER" />
    <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER" />
    <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL" />
    <STRING id="STR_ID_UMMS_RESTRICTED_MODE_MSG_SIZE_EXCEED" />
# 298 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_FROM_SIM1" />
# 308 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_DOWNLOAD_FROM_SIM1" />
    <STRING id="STR_ID_UMMS_DOWNLOAD_FROM_SIM2" />
# 334 "temp/res/MMSApp.c"
    <STRING id="STR_ID_CONFM_DELETE_READ_REPORT_MMS"/>
# 348 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_DOWNLOAD_IN_PROGRESS" />
    <STRING id="STR_UMMS_NO_ENOUGH_WORKING_SPACE_ID" />






    <STRING id="STR_ID_UMMS_ROOT_DIR_FULL" />



    <STRING id="STR_ID_UMMS_CANCELED" />


   <STRING id="STR_ID_UMMS_NOTIFICATION_EXPIRED" />
# 373 "temp/res/MMSApp.c"
   <STRING id="STR_ID_MMA_RESULT_FAIL" />
   <STRING id="STR_ID_UMMS_OPTIONS_MSG_SIZE_EXCEED" />



    <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_MSG_NUM_REACHED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_MSG_SIZE_REACHED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_CORRUPTED" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_IN_USE" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_IO" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_UNSUPPORT_CONTENT" />



   <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_LARGE" />




   <STRING id="STR_ID_UMMS_DEFFERED" />



   <STRING id="STR_ID_UMMS_CANCEL_SEND_CNFRM" />






   <STRING id="STR_ID_UMMS_UPDATING_STATUS" />
   <STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_PARAMETER" />




        <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS" />
# 422 "temp/res/MMSApp.c"
        <STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_PHONE" />
        <STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_CARD" />
        <STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE" />
        <STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_CARD" />
        <STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_PHONE_ASK" />
        <STRING id="STR_ID_UMMS_OPTIONS_MOVE_TO_CARD_ASK" />
        <STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE_ASK" />
        <STRING id="STR_ID_UMMS_OPTIONS_COPY_TO_CARD_ASK" />
        <STRING id="STR_ID_UMMS_COPY_TO_CARD_DONE" />
        <STRING id="STR_ID_UMMS_COPY_TO_PHONE_DONE" />
        <STRING id="STR_ID_UMMS_MOVE_TO_CARD_DONE" />
        <STRING id="STR_ID_UMMS_MOVE_TO_PHONE_DONE" />

        <STRING id="STR_ID_UMMS_PHONE_FULL_USE_CARD_MEM" />
        <STRING id="STR_ID_UMMS_CARD_FULL_USE_PHONE_MEM" />
        <STRING id="STR_ID_UMMS_CARD_NOT_PRESENT_USE_PHONE" />
# 450 "temp/res/MMSApp.c"
        <STRING id="STR_ID_UMMS_DELETE_CONRM" />
# 465 "temp/res/MMSApp.c"
        <STRING id="STR_ID_UMMS_USE_DETAILS_GREETING_TEXT" />
        <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER" />
<STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL" />
        <STRING id="STR_ID_UMMS_OPTIONS_USE_DETAILS_URL" />
      <STRING id="STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK" />
        <STRING id="STR_ID_UMMS_USE_DETAILS_NO_URL" />
    <STRING id="STR_ID_UMMS_USE_DETAILS_NO_NUMBER" />
    <STRING id="STR_ID_UMMS_USE_DETAILS_NO_EMAIL_ID" />
    <STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_ALL" />
    <STRING id="STR_ID_UMMS_CALL_SENDER" />

        <STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_SMS" />
        <STRING id="STR_ID_UMMS_INBOX_OPTIONS_REPLY_MMS" />

        <STRING id="STR_ID_UMMS_OPTIONS_SAVE_OBJECTS" />



        <STRING id="STR_ID_UMMS_FAILED" />






        <STRING id="STR_ID_UMMS_OBJECTS_ATTACHMENT_LIST" />

        <STRING id="STR_ID_UMMS_DR_STATUS_EXPIRED" />
        <STRING id="STR_ID_UMMS_DR_STATUS_RETRIEVED" />
        <STRING id="STR_ID_UMMS_DR_STATUS_REJECTED" />
        <STRING id="STR_ID_UMMS_DR_STATUS_UNRECOGNISED" />
        <STRING id="STR_ID_UMMS_DR_STATUS_INDETERMINATE" />
        <STRING id="STR_ID_UMMS_DR_STATUS_FORWARDED" />
        <STRING id="STR_ID_UMMS_DR_STATUS_UNREACHABLE" />
        <STRING id="STR_ID_UMMS_DR_STATUS_NO_READ" />

 <STRING id="STR_ID_UMMS_WAP_MAX_SIZE_EXCEEDS" />
# 514 "temp/res/MMSApp.c"
    <STRING id="STR_ID_UMMS_CANCEL_SEND_RR" />




    <STRING id="STR_ID_UMMS_FAILED_TO_DISPLAY_JSR_MMS" />
        <STRING id="STR_ID_UMMS_EXPIRE_TIME" />




        <STRING id="STR_ID_UMMS_SIZE" />
# 540 "temp/res/MMSApp.c"
        <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_SLIDE_NUM_REACHED" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_MAX_ATTACHMENT_NUM_REACHED" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_MSGID" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_INVALID_FOLDER" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_PARSE" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_MSGID_IS_USING" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_CREATION_MODE_MAX_MSG_SIZE_REACHED" />
        <STRING id="STR_ID_MMA_RESULT_FAIL_FILE_ACCESS_IN_USB_MODE" />
        <STRING id="STR_ID_UMMS_CORRUPT_AND_DELETE" />
        <STRING id="STR_ID_UMMS_UNSUPPORTED_MMS_AND_DELETE" />
        <STRING id="STR_ID_UMMS_CANCEL_SEND" />
        <STRING id="STR_ID_UMMS_FROM" />






        <STRING id="STR_ID_UMMS_CREATION_DATE" />
        <STRING id="STR_ID_UMMS_RECEIVE_DATE" />

        <STRING id="STR_ID_UMMS_STATUS" />
# 572 "temp/res/MMSApp.c"
    <STRING id="STR_ID_MMS_VIEWER_SEND_RR_CONFIRM" />
    <STRING id="STR_ID_MMS_VIEWER_OUT_OF_MEMORY" />
    <STRING id="STR_ID_MMS_VIEWER_FILE_ERROR" />
    <STRING id="STR_ID_MMS_VIEWER_APP" />
# 589 "temp/res/MMSApp.c"
<STRING id="STR_UC_EDIT_CONTENT_ID"/>
<STRING id="STR_UC_EDIT_TEXT_ID"/>
<STRING id="STR_UC_INSERT_SLIDE_ID"/>
<STRING id="STR_UC_INSERT_IMAGE_ID"/>
<STRING id="STR_UC_INSERT_VIDEO_ID"/>



<STRING id="STR_UC_DELETE_SLIDE_ID"/>
<STRING id="STR_UC_DELETE_VIDEO_ID"/>
<STRING id="STR_UC_DELETE_IMAGE_ID"/>



<STRING id="STR_UC_DELETE_ID"/>
<STRING id="STR_UC_INSERT_ID"/>
<STRING id="STR_UC_ADD_RECIPIENT_TO"/>




<STRING id="STR_UC_MMS_SEND_ID"/>
<STRING id="STR_ID_UMMS_OPTIONS_RECIPIENT_TO_LIST"/>




<STRING id="STR_UC_ADD_ADDRESS"/>
<STRING id="STR_UC_EDIT_ADDRESS"/>
<STRING id="STR_UC_REMOVE_ADDRESS"/>
<STRING id="STR_UC_ADD_FROM_PHONEBOOK"/>
<STRING id="STR_ID_UMMS_COMPOSER_OPTION"/>
<STRING id="STR_UMMS_UC_NUMBER_LENGTH_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_REMOVED_ID"/>
<STRING id="STR_ID_UMMS_UC_RECIPIENT_NUMBER_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_MSG_SIZE_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_RESTRICTED_MODE_MSG_SIZE_EXCEED_ID"/>
<STRING id="STR_ID_UMMS_UC_PROHIBIT_BY_CREATION_MODE_ID"/>
<STRING id="STR_OPTION_SAVE_DRAFT_ID"/>
<STRING id="STR_OPTION_PREVIEW_MMS_ID"/>
<STRING id="STR_OPTION_EDIT_SUBJECT_ID"/>




<STRING id="STR_UMMS_NO_RECIPIENT"/>
<STRING id="STR_UMMS_MOVE_TO_ATTACHMENT_ID"/>
<STRING id="STR_UMMS_FAILED_TO_ADD_MEDIA_ID"/>
<STRING id="STR_UMMS_REMOVE_ASK_ID"/>
<STRING id="STR_UMMS_CARD_NOT_PRESENT_CONFIRM"/>
<STRING id="STR_UMMS_MAX_MSG_CARD_CONFIRM"/>
<STRING id="STR_UMMS_MAX_MSG_PHONE_CONFIRM"/>
# 649 "temp/res/MMSApp.c"
    <!-----------------------------------------------------Image Resource Area------------------------------------------------------>

    <IMAGE id="IMG_ID_UMMS_WRITE_MESSAGE">"..\\\\..\\\\Customer\\\\Images""\\\\PLUTO_ENCODE""\\\\MainLCD\\\\MMS\\\\SB_WRITE.bmp","mms menu icon write message"</IMAGE>
# 672 "temp/res/MMSApp.c"
    <IMAGE id="IMG_ID_UMMS_ATTACHMENT_LIST" > "..\\\\..\\\\Customer\\\\Images""\\\\PLUTO_ENCODE""\\\\MainLCD\\\\MMS\\\\SB_LIST.bmp"</IMAGE>


<!------------------------------------------------------callback manager reciever part---------------------------------------------------------->

       <RECEIVER id="EVT_ID_SRV_ASM_SUCCESS" proc="mmi_umms_app_core_asm_success"/>
       <RECEIVER id="EVT_ID_SRV_ASM_STOP" proc="mmi_umms_app_core_asm_stop"/>
       <RECEIVER id="EVT_ID_SRV_ASM_CANCEL" proc="mmi_umms_app_core_asm_cancel"/>



    <RECEIVER id="EVT_ID_SRV_FMGR_NOTIFICATION_DEV_PLUG_OUT" proc="mmi_umms_uc_sd_card_plug_out_hdlr_cb"/>







    <!------------------------------------------------------Menu Resource Area------------------------------------------------------>
# 708 "temp/res/MMSApp.c"
    <MENU id="MENU_ID_UMMS_MESSAGE_SETTINGS_FOR_COMMON_SETTINGS" type="ORIGINAL" str="STR_ID_UMMS_MMS_SETTINGS" img="IMG_MESSAGE_MMS_MENUENTRY" >
        <MENUITEM_ID>MENU_ID_UMMS_MMS_SETTINGS_EDIT_PROFILE</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_MMS_SETTINGS</MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_EDIT_PROFILE" str="STR_GLOBAL_DATA_ACCOUNT"/>


        <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_ON" str="STR_GLOBAL_ON"/>
        <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_OFF" str="STR_GLOBAL_OFF"/>
# 847 "temp/res/MMSApp.c"
        <MENU id="MENU_ID_SENDING_SETTINGS_DELIVERY_REPORT" type="ORIGINAL" str="STR_ID_UMMS_DELIVERY_REPORT" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>
    </MENU>


        <MENU id="MENU_ID_SENDING_SETTINGS_READ_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT" flag = "RADIO">

        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>
    </MENU>


        <MENUITEM id="MENU_ID_SENDING_SETTINGS_LOW" str="STR_GLOBAL_LOW"/>
        <MENUITEM id="MENU_ID_SENDING_SETTINGS_HIGH" str="STR_GLOBAL_MEDIUM"/>
        <MENUITEM id="MENU_ID_SENDING_SETTINGS_MEDIUM" str="STR_GLOBAL_HIGH"/>
        <MENU id="MENU_ID_SENDING_SETTINGS_PRIORITY" type="ORIGINAL" str="STR_GLOBAL_PRIORITY" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_LOW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_HIGH </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_MEDIUM </MENUITEM_ID>
    </MENU>
# 889 "temp/res/MMSApp.c"
        <MENU id="MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>
    </MENU>
# 908 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_SENDING_SETTINGS_DELIVERY_REPORT_EXT" str="STR_ID_UMMS_DELIVERY_REPORT"/>

    <MENUITEM id="MENU_ID_SENDING_SETTINGS_READ_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_REQ_READ_REPORT"/>

    <MENUITEM id="MENU_ID_SENDING_SETTINGS_PRIORITY_EXT" str="STR_GLOBAL_PRIORITY"/>






    <MENUITEM id="MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE_EXT" str="STR_ID_UMMS_SETTINGS_SEND_AND_SAVE"/>
# 944 "temp/res/MMSApp.c"
        <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_IMMEDAITE" str="STR_ID_UMMS_SETTINGS_IMMEDIATE"/>
        <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_DEFERRED" str="STR_ID_UMMS_DEFFERED"/>



        <MENU id="MENU_ID_RETRIEVAL_SETTINGS_HOME_NW" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_IMMEDAITE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DEFERRED </MENUITEM_ID>
    </MENU>
# 979 "temp/res/MMSApp.c"
   <MENU id="MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT" flag = "RADIO" >
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_ON </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_OFF </MENUITEM_ID>
    </MENU>



    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_SEND" str="STR_GLOBAL_SEND"/>
        <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_SEND_ON_REQ" str="STR_ID_UMMS_SETTINGS_ON_REQUEST"/>
        <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_NEVER_SEND" str="STR_ID_UMMS_SETTINGS_NEVER_SEND"/>




        <MENU id="MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT" type="ORIGINAL" str="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_SEND_ON_REQ </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_NEVER_SEND </MENUITEM_ID>
    </MENU>




    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_HOME_NW_EXT" str="STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL_SLIM"/>
# 1013 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_SEND_DELV_REPORT"/>

    <MENUITEM id="MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT_EXT" str="STR_ID_UMMS_SETTINGS_SEND_READ_REPORT"/>




    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_EXT" str="STR_ID_UMMS_MMS_PREFER_STORAGE"/>
# 1045 "temp/res/MMSApp.c"
 <MENU id="MENU_ID_UMMS_MMS_SETTINGS" type="ORIGINAL" str="STR_ID_UMMS_MESSAGE_SETTINGS_COMMON_SETTINGS" >






        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_HOME_NW_EXT </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ANON_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_ADV_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_DELIVERY_REPORT_EXT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_RETRIEVAL_SETTINGS_READ_REPORT_EXT </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_SENDING_SETTINGS_SEND_AND_SAVE_EXT </MENUITEM_ID>






        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_EXT </MENUITEM_ID>






        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS </MENUITEM_ID>
    </MENU>
# 1105 "temp/res/MMSApp.c"
    <MENU id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE" type="ORIGINAL" str="STR_ID_UMMS_MMS_PREFER_STORAGE" flag = "RADIO">
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_CARD </MENUITEM_ID>
    </MENU>
# 1117 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_PHONE" str="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_PREFER_STORAGE_CARD" str="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>

    <MENU id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS" type="OPTION" str="STR_GLOBAL_MEMORY_STATUS">

        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_PHONE </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_CARD </MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_PHONE" str="STR_ID_UMMS_MMS_PREFER_STORAGE_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_MMS_SETTINGS_MEMORY_STATUS_CARD" str="STR_ID_UMMS_MMS_PREFER_STORAGE_CARD"/>
# 1193 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_PREVIEW_GO_TO" str="STR_GLOBAL_GO_TO"/>

    <MENU id="MENU_ID_UMMS_PREVIEW_OPTION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_GO_TO </MENUITEM_ID>
    </MENU>



    <MENU id="MENU_ID_UMMS_READ_REPORT_SENDING_OPTION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_CANCEL_SEND_RR" str="STR_ID_UMMS_CANCEL_SEND_RR"/>



    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_NEW_MMS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTION_REPLY_SMS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_REPLY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_REPLY_ALL </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_CALL_SENDER </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_FORWARD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_LOCK </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_UNLOCK </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_CONTACT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_READ </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_UNREAD </MENUITEM_ID>





        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>


    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_NOTIFICATION" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTIONS_DOWNLOAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTIONS_CANCEL_DOWNLOAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_DELIVERY_REPORT" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_READ </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_INBOX_OPTION_MARK_AS_UNREAD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>

    <MENU id="MENU_ID_UMMS_INBOX_OPTIONS_JAVA_MMS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_CLEAR_ALL_EVENT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_HS_INBOX_GO_TO </MENUITEM_ID>
    </MENU>
# 1352 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_OPTION_REPLY_SMS" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_SMS"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_REPLY" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_MMS"/>
# 1364 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_VIEW" str="STR_GLOBAL_VIEW"/>

    <MENUITEM id="MENU_ID_UMMS_OPTIONS_REPLY_ALL" str="STR_ID_UMMS_INBOX_OPTIONS_REPLY_ALL"/>
    <MENUITEM id="MENU_ID_UMMS_CALL_SENDER" str="STR_ID_UMMS_CALL_SENDER"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_CONTACT" str="STR_GLOBAL_SAVE_TO_PHONEBOOK"/>


    <MENUITEM id="MENU_ID_UMMS_OPTIONS_FORWARD" str="STR_GLOBAL_FORWARD"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_DELETE" str="STR_GLOBAL_DELETE"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE" str="STR_GLOBAL_EDIT"/>

    <MENU id="MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS" type="OPTION" str="STR_ID_UMMS_OPTIONS_SAVE_OBJECTS">
        <MENUITEM_ID>MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_TEXT_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_CURRENT_ATTACHMENT_AS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS</MENUITEM_ID>
    </MENU>


    <MENUITEM id="MENU_ID_UMMS_OPTIONS_PROPERTIES" str="STR_GLOBAL_DETAILS"/>
# 1401 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE" str="STR_ID_UMMS_OPTIONS_COPY_TO_PHONE"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_COPY_TO_CARD" str="STR_ID_UMMS_OPTIONS_COPY_TO_CARD"/>


    <MENUITEM id="MENU_ID_UMMS_INBOX_OPTIONS_DOWNLOAD" str="STR_GLOBAL_DOWNLOAD"/>



    <MENU id="MENU_ID_UMMS_OPTIONS_USE_DETAILS" type="OPTION" str="STR_ID_UMMS_OPTIONS_USE_DETAILS">
        <MENUITEM_ID>MENU_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTION_USE_DETAILS_URL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_SENDER</MENUITEM_ID>
        <MENUITEM_ID>MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL</MENUITEM_ID>
    </MENU>

    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_NUMBER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_REC_EMAIL"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_SENDER" str="STR_ID_UMMS_USE_DETAILS_SENDER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER"/>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL"/>
    <MENUITEM id="MENU_ID_UMMS_OPTION_USE_DETAILS_URL" str="STR_ID_UMMS_OPTIONS_USE_DETAILS_URL"/>

    <MENU id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_USE_NUMBER" type="OPTION">
        <MENUITEM_ID>MENU_ID_UMMS_USE_DETAILS_ADDRESSES_CALL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHBOOK</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_SMS</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_MMS</MENUITEM_ID>
    </MENU>
    <MENU id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_USE_EMAIL" type="OPTION">
        <MENUITEM_ID>MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_TO_CONTACT</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_EMAIL</MENUITEM_ID>
        <MENUITEM_ID >MENU_ID_UMMS_USE_DETAILS_SEND_MMS</MENUITEM_ID>
    </MENU>





    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_SEND_SMS" str="STR_GLOBAL_SEND_TEXT_MESSAGE"/>





    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHBOOK" str="STR_GLOBAL_SAVE_TO_PHONEBOOK"/>
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_CALL" str="STR_GLOBAL_DIAL"/>
# 1460 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_GO_TO" str="STR_GLOBAL_GO_TO"/>
    <MENUITEM id="MENU_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK" str="STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK"/>







    <MENU id="MENU_ID_UMMS_OUTBOX_OPTIONS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_RESEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_CANCEL_SEND </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OUTBOX_OPTIONS_MESSAGE_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
    </MENU>
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_SEND" str="STR_GLOBAL_SEND"/>
# 1505 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_OPTIONS_RESEND" str="STR_ID_UMMS_RESEND"/>
# 1521 "temp/res/MMSApp.c"
    <MENUITEM id="MENU_ID_UMMS_OUTBOX_OPTIONS_CANCEL_SEND" str="STR_ID_UMMS_CANCEL_SEND"/>



    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_TEXT_AS" str="STR_GLOBAL_TEXT"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS" str="STR_GLOBAL_PICTURE"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS" str="STR_ID_UMMS_SETTINGS_SIGNATURE_AUDIO"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS" str="STR_GLOBAL_VIDEO"/>
    <MENUITEM id="MENU_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS" str="STR_ID_UMMS_OBJECTS_ATTACHMENT_LIST"/>







    <MENU id="MENU_ID_UMMS_SENT_OPTIONS" type="OPTION" >
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_FORWARD </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>





        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
                    <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
                <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELIVERY_STATUS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_READ_STATUS </MENUITEM_ID>
    </MENU>


    <MENU id="MENU_ID_UMMS_DRAFT_OPTIONS" type="OPTION" >

        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_AUDIO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_PHOTO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_DYNAMIC_VIDEO_LABEL_OPTIONS_VIEW </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MANUAL_PLAY_VIEW_FROM_START </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_EDIT_MESSAGE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_DELETE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_DEL_ALL_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_SORT_BY_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SAVE_OBJECTS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_TEMPLATE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_OPT </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UM_MS_DELETE_OPT</MENUITEM_ID>





        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_PHONE </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_COPY_TO_CARD </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_USE_DETAILS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_PROPERTIES </MENUITEM_ID>
    </MENU>




        <MENU id="MENU_ID_UMMS_COMPOSER_OPTIONS" type="OPTION" >
            <MENUITEM_ID> MENU_ID_UMMS_EDIT_TEXT </MENUITEM_ID>
                <MENU id="MENU_ID_UMMS_INSERT" type="OPTION" str="STR_UC_INSERT_ID">
                        <MENUITEM_ID> MENU_ID_UMMS_INSERT_SLIDE </MENUITEM_ID>
                        <MENUITEM_ID> MENU_ID_UMMS_INSERT_IMAGE </MENUITEM_ID>
                        <MENUITEM_ID> MENU_ID_UMMS_INSERT_VIDEO </MENUITEM_ID>
                        <MENUITEM_ID> MENU_ID_UMMS_INSERT_SOUND </MENUITEM_ID>



                </MENU>
      <MENU id="MENU_ID_UMMS_DELETE" type="OPTION" str="STR_UC_DELETE_ID">
                <MENUITEM_ID> MENU_ID_UMMS_DELETE_SLIDE </MENUITEM_ID>
                <MENUITEM_ID> MENU_ID_UMMS_DELETE_IMAGE </MENUITEM_ID>
                <MENUITEM_ID> MENU_ID_UMMS_DELETE_SOUND </MENUITEM_ID>
                <MENUITEM_ID> MENU_ID_UMMS_DELETE_VIDEO </MENUITEM_ID>



      </MENU>
        </MENU>

        <MENUITEM id="MENU_ID_UMMS_EDIT_CONTENT" str="STR_UC_EDIT_CONTENT_ID"/>
        <MENUITEM id="MENU_ID_UMMS_EDIT_SUBJECT" str="STR_OPTION_EDIT_SUBJECT_ID"/>
        <MENUITEM id="MENU_ID_UMMS_SAVE_TO_DRAFT" str="STR_GLOBAL_SAVE"/>
        <MENUITEM id="MENU_ID_UMMS_PREVIEW_MMS" str="STR_OPTION_PREVIEW_MMS_ID"/>
        <MENUITEM id="MENU_ID_UMMS_EDIT_TEXT" str="STR_UC_EDIT_TEXT_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_SLIDE" str="STR_UC_INSERT_SLIDE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_IMAGE" str="STR_UC_INSERT_IMAGE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_INSERT_VIDEO" str="STR_UC_INSERT_VIDEO_ID"/>






        <MENUITEM id="MENU_ID_UMMS_DELETE_SLIDE" str="STR_UC_DELETE_SLIDE_ID"/>
        <MENUITEM id="MENU_ID_UMMS_DELETE_IMAGE" str="STR_UC_DELETE_IMAGE_ID"/>



        <MENUITEM id="MENU_ID_UMMS_DELETE_VIDEO" str="STR_UC_DELETE_VIDEO_ID"/>




       <MENUITEM id="MENU_ID_UMMS_ADD_RECIPIENT_TO" str="STR_UC_ADD_RECIPIENT_TO"/>
# 1661 "temp/res/MMSApp.c"
        <MENUITEM id="MENU_ID_UMMS_OPTIONS_SLIM_SEND" str="STR_UC_MMS_SEND_ID"/>

       <MENUITEM id="MENU_ID_UMMS_ADD_ADDRESS" str="STR_UC_ADD_ADDRESS"/>
       <MENUITEM id="MENU_ID_UMMS_EDIT_ADDRESS" str="STR_UC_EDIT_ADDRESS"/>
       <MENUITEM id="MENU_ID_UMMS_REMOVE_ADDRESS" str="STR_UC_REMOVE_ADDRESS"/>
        <MENUITEM id="MENU_ID_UMMS_ADD_FROM_PHONEBOOK_MMS" str="STR_UC_ADD_FROM_PHONEBOOK"/>
                <MENUITEM id="MENU_ID_UMMS_COMPOSER_OPTIONS" str="STR_ID_UMMS_COMPOSER_OPTION"/>


        <MENU id="MENU_ID_UMMS_OPTIONS_SLIM" type="ORIGINAL" str="STR_GLOBAL_EDIT">
        <MENUITEM_ID> MENU_ID_UMMS_OPTIONS_SLIM_SEND </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_TO </MENUITEM_ID>

        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_CC </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_ADD_RECIPIENT_BCC </MENUITEM_ID>



        <MENUITEM_ID> MENU_ID_UMMS_EDIT_SUBJECT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_EDIT_CONTENT</MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_PREVIEW_MMS </MENUITEM_ID>
        <MENUITEM_ID> MENU_ID_UMMS_SAVE_TO_DRAFT</MENUITEM_ID>
    </MENU>

               <MENU id="MENU_ID_UMMS_RECIPIENT_SLIM" type="OPTION" >
                  <MENUITEM_ID> MENU_ID_UMMS_ADD_ADDRESS</MENUITEM_ID>
            <MENUITEM_ID> MENU_ID_UMMS_EDIT_ADDRESS</MENUITEM_ID>
            <MENUITEM_ID> MENU_ID_UMMS_REMOVE_ADDRESS </MENUITEM_ID>
            <MENUITEM_ID> MENU_ID_UMMS_ADD_FROM_PHONEBOOK_MMS</MENUITEM_ID>
        </MENU>
# 1712 "temp/res/MMSApp.c"
</APP>
