/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_tencent_mcare_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_TENCENT_MCARE_DEF_H
#define _MMI_RP_APP_TENCENT_MCARE_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_MCARE_MAIN = 32636 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_TENCENT_MCARE_MENU_MAX
}mmi_rp_app_tencent_mcare_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_MCARE_MAIN = 32636 + 1, /* BASE_ID + 1 */
    STR_MCARE_QQ,
    STR_MCARE_QQBROWSER,
    STR_MCARE_QQFARM,
    STR_MCARE_QQPASTURE,
    STR_MCARE_RUNNING,
    STR_MCARE_QQ_RUNNING,
    STR_MCARE_INSERT_VALID_SIM,
    STR_MCARE_IS_ON_FLY_MODE,
    STR_MCARE_STORAGE_ERROR_NOTE,
    STR_MCARE_SIM_ERROR,
    STR_MCARE_NOT_ENOUGH_MEM,
    STR_MCARE_STORAGE_NO_SPACE,
    STR_MCARE_FILE_CORRUPT_RESTART,
    STR_MCARE_LOAD_FAIL,
    STR_MCARE_FILE_CORRUPT_ERR,
    STR_MCARE_EXEC_FAIL,
    STR_MCARE_NETWORK_NOT_READY,
    STR_MCARE_USB_MODE,
    STR_MCARE_LAST,
    STR_TENCENT_MCARE_QQ_ONLINE,
    STR_TENCENT_MCARE_QQ_INVISBLE,
    STR_TENCENT_MCARE_QQ_OFFLINE,
    STR_TENCENT_MCARE_QQ_AWAY,
    STR_TENCENT_MCARE_QQ_HAVEMSG,
    MMI_RP_APP_TENCENT_MCARE_STR_MAX
}mmi_rp_app_tencent_mcare_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    SCR_ID_MCARE_LIST = 32636 + 1, /* BASE_ID + 1 */
    GRP_ID_MCARE_LIST,
    GRP_ID_MCARE_TOTAL,
    MMI_RP_APP_TENCENT_MCARE_SCR_MAX
}mmi_rp_app_tencent_mcare_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_VAPP_MCARE_UPDATE_NCENTER = 32636 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_TENCENT_MCARE_EVENT_MAX
}mmi_rp_app_tencent_mcare_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_TENCENT_MCARE_VXML_LAYOUT_MAX
} mmi_rp_app_tencent_mcare_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_MCARE_MAIN = 32636 + 1, /* BASE_ID + 1 */
    IMG_MCARE_STAT_MCR,
    IMG_MCARE_STAT_QQ_ON,
    IMG_MCARE_STAT_QQ_OFF,
    IMG_MCARE_STAT_QQ_AWAY,
    IMG_MCARE_STAT_QQ_INVISBLE,
    IMG_MCARE_STAT_QQ_MESSEGE,
    IMG_MCARE_STAT_CONTACT_ON,
    IMG_MCARE_NCENTER_MCR,
    IMG_MCARE_NCENTER_QQ_ON,
    IMG_MCARE_NCENTER_QQ_OFF,
    IMG_MCARE_NCENTER_QQ_AWAY,
    IMG_MCARE_NCENTER_QQ_INVISBLE,
    IMG_MCARE_NCENTER_QQ_MESSEGE,
    MMI_RP_APP_TENCENT_MCARE_IMG_MAX
}mmi_rp_app_tencent_mcare_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_TENCENT_MCARE_DEF_H */
