/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_fmrdo_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_FMRDO_DEF_H
#define _MMI_RP_APP_FMRDO_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_ID_FMRDO_MAIN = 35399 + 1, /* BASE_ID + 1 */
    MENU_ID_FMRDO_CHANNEL_LIST,
    MENU_ID_FMRDO_MANUAL_INPUT,
    MENU_ID_FMRDO_PRESET_AUTO_SEARCH,
    MENU_ID_FMRDO_SETTINGS,
    MENU_ID_FMRDO_RECORD,
    MENU_ID_FMRDO_FILE_LIST,
    MENU_ID_FMRDO_MAIN_OPTION,
    MENU_ID_FMRDO_CHANNEL_OPT_PLAY,
    MENU_ID_FMRDO_CHANNEL_OPT_DELETE,
    MENU_ID_FMRDO_CHANNEL_OPT_EDIT,
    MENU_ID_FMRDO_CHANNEL_OPTION,
    MMI_RP_APP_FMRDO_MENU_MAX
}mmi_rp_app_fmrdo_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_FMRDO_TITLE = 35399 + 1, /* BASE_ID + 1 */
    STR_ID_FMRDO_CHANNEL_LIST,
    STR_ID_FMRDO_MANUAL_INPUT,
    STR_ID_FMRDO_PRESET_AUTO_SEARCH,
    STR_ID_FMRDO_BACKGROUND_PLAY,
    STR_ID_FMRDO_PRESET_LIST,
    STR_ID_FMRDO_CHANNEL_NAME,
    STR_ID_FMRDO_FREQUENCY,
    STR_ID_FMRDO_VALID_FM_BANDWIDTH,
    STR_ID_FMRDO_VALID_FM_DECIMAL,
    STR_ID_FMRDO_NEW_CHANNEL,
    STR_ID_FMRDO_SET_CH_LIST,
    STR_ID_FMRDO_POWER_ON_FIRST,
    STR_ID_FMRDO_LOUD_SPEAKER,
    STR_ID_FMRDO_CANCEL_ASK,
    STR_ID_FMRDO_RECORD,
    STR_ID_FMRDO_APPEND,
    STR_ID_FMRDO_FILE_LIST,
    STR_ID_FMRDO_RECORD_FORMAT,
    STR_ID_FMRDO_RECORD_STORAGE,
    STR_ID_FMRDO_FORMAT_AMR,
    STR_ID_FMRDO_FORMAT_WAV,
    STR_ID_FMRDO_BAD_FORMAT,
    STR_ID_FMRDO_INVALID_FORMAT,
    STR_ID_FMRDO_DEVICE_BUSY,
    STR_ID_FMRDO_OPEN_FILE_ERROR,
    STR_ID_FMRDO_NO_CARD,
    STR_ID_FMRDO_WRITE_PROTECTION_ERROR,
    STR_ID_FMRDO_RECORD_IN_BT_SCO,
    STR_ID_FMRDO_RECORD_FAILED,
    STR_ID_FMRDO_RECORD_QUALITY,
    STR_ID_FMRDOREC_SIZE_LIMIT,
    STR_ID_FMRDO_RDS_SETTING,
    STR_ID_FMRDO_RDS_AF_SERVICE,
    STR_ID_FMRDO_RDS_TP_SERVICE,
    MMI_RP_APP_FMRDO_STR_MAX
}mmi_rp_app_fmrdo_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_FMRDO = 35399 + 1, /* BASE_ID + 1 */
    SCR_ID_FMRDO_BASE,
    SCR_ID_FMRDO_MAIN,
    SCR_ID_FMRDO_MAIN_OPTION,
    SCR_ID_FMRDO_CHANNEL_LIST,
    SCR_ID_FMRDO_MANUAL_INPUT,
    SCR_ID_FMRDO_PRESET_LIST_CONFIRM,
    SCR_ID_FMRDO_SETTINGS,
    SCR_ID_FMRDO_CHANNEL_OPTION,
    SCR_ID_FMRDO_SEARCHING,
    SCR_ID_FMRDO_A2DP_CONNECTING,
    SCR_ID_FMRDO_SUBLCD_MAIN,
    SCR_ID_FMRDO_SUBLCD_OPTION,
    SCR_ID_FMRDO_SUBLCD_SEARCHING,
    SCR_ID_FMRDO_SCHEDULE_LIST,
    SCR_ID_FMRDO_SCHEDULE_RENAME,
    SCR_ID_FMRDO_SCHEDULE_OPTIONS,
    SCR_ID_FMRDO_SCHEDULE_EDITOR,
    SCR_ID_FMRDO_SCHEDULE_SETTINGS,
    SCR_ID_FMRDO_SCHEDULE_CHANNEL_OPTIONS,
    SCR_ID_FMRDO_SCHEDULE_SETTINGS_REPEAT,
    SCR_ID_FMRDO_SCHEDULE_ALARM_PLAYING,
    SCR_ID_FMRDO_RDS_SETTINGS,
    MMI_RP_APP_FMRDO_SCR_MAX
}mmi_rp_app_fmrdo_scr_enum;
/******************** Screen resource IDs - finish ********************/


/******************** Timer resource IDs - begin ********************/
typedef enum
{
    FMRDO_TWINKLE_FREQUENCY_TIMER = 35399 + 1, /* BASE_ID + 1 */
    FMRDO_REPEAT_STEP_TIMER,
    MMI_RP_APP_FMRDO_TIMER_MAX
}mmi_rp_app_fmrdo_timer_enum;
/******************** Timer resource IDs - finish ********************/


/******************** Events resource IDs - begin ********************/
typedef enum
{
    EVT_ID_FMRDO_A2DP_CONNECT = 35399 + 1, /* BASE_ID + 1 */
    MMI_RP_APP_FMRDO_EVENT_MAX
}mmi_rp_app_fmrdo_event_enum;
/******************** Events resource IDs - begin ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_FMRDO_VXML_LAYOUT_MAX
} mmi_rp_app_fmrdo_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_FMRDO_BACKGROUND_PLAY = 35399 + 1, /* BASE_ID + 1 */   /*         BYTE */ 
    NVRAM_FMRDO_SKIN,                                           /*         BYTE */ 
    NVRAM_FMRDO_VOLUME,                                         /*         BYTE */ 
    NVRAM_FMRDO_RECORD_FORMAT,                                  /*         BYTE */ 
    NVRAM_FMRDO_RECORD_STORAGE,                                 /*         BYTE */ 
    NVRAM_FMRDO_SPEAKER_STATUS,                                 /*         BYTE */ 
    NVRAM_FMRDO_RDS_SETTING,                                    /*         BYTE */ 
    NVRAM_FMRDO_RDS_TP_SETTING,                                 /*         BYTE */ 
    NVRAM_FMRDO_RDS_AF_SETTING,                                 /*         BYTE */ 
    NVRAM_FMRDO_RECORD_QUALITY,                                 /*         BYTE */ 
    NVRAM_FMRDO_CHANNEL_MONO,                                   /*         BYTE */ 
    NVRAM_FMRDO_MUTE,                                           /*         BYTE */ 
    NVRAM_FMRDO_LAST_CHANNEL,                                   /*        SHORT */ 
    NVRAM_FM_FM_RADIO_CHANNEL_1,                                /*        SHORT */ 
    NVRAM_FM_FM_RADIO_CHANNEL_2,                                /*        SHORT */ 
    NVRAM_FM_FM_RADIO_CHANNEL_3,                                /*        SHORT */ 
    MMI_RP_APP_FMRDO_MMI_CACHE_MAX
} mmi_rp_app_fmrdo_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_FMRDO_SKIN_1_TITLE_BG = 35399 + 1, /* BASE_ID + 1 */
    IMG_ID_FMRDO_SKIN_1_TUNER_SCALE,
    IMG_ID_FMRDO_SKIN_1_TUNER_SCALE_INDICATOR,
    IMG_ID_FMRDO_SKIN_1_VOLUME,
    IMG_ID_FMRDO_SKIN_1_VOLUME_BG,
    IMG_ID_FMRDO_SKIN_1_POWER_BUTTON_ON,
    IMG_ID_FMRDO_SKIN_1_POWER_BUTTON_OFF,
    IMG_ID_FMRDO_SKIN_1_SEARCH_UP_BUTTON,
    IMG_ID_FMRDO_SKIN_1_SEARCH_DOWN_BUTTON,
    IMG_ID_FMRDO_SKIN_1_STEP_UP_BUTTON,
    IMG_ID_FMRDO_SKIN_1_STEP_DOWN_BUTTON,
    IMG_ID_FMRDO_SKIN_1_BUTTON_BG,
    IMG_ID_FMRDO_SKIN_1_BUTTON_DISABLE,
    IMG_ID_FMRDO_SKIN_1_BUTTON_HIGHLIGHT,
    IMG_ID_FMRDO_SKIN_1_REC,
    IMG_ID_FMRDO_SKIN_1_REC_PAUSE,
    IMG_ID_FMRDO_SKIN_1_NUM_0,
    IMG_ID_FMRDO_SKIN_1_NUM_1,
    IMG_ID_FMRDO_SKIN_1_NUM_2,
    IMG_ID_FMRDO_SKIN_1_NUM_3,
    IMG_ID_FMRDO_SKIN_1_NUM_4,
    IMG_ID_FMRDO_SKIN_1_NUM_5,
    IMG_ID_FMRDO_SKIN_1_NUM_6,
    IMG_ID_FMRDO_SKIN_1_NUM_7,
    IMG_ID_FMRDO_SKIN_1_NUM_8,
    IMG_ID_FMRDO_SKIN_1_NUM_9,
    IMG_ID_FMRDO_SKIN_1_NUM_COL,
    IMG_ID_FMRDO_RDS_SKIN_1_RDS_UP,
    IMG_ID_FMRDO_RDS_SKIN_1_RDS_DOWN,
    IMG_ID_FMRDO_RDS_SKIN_1_RDS_DISABLE,
    IMG_ID_FMRDO_RDS_SKIN_1_TP_UP,
    IMG_ID_FMRDO_RDS_SKIN_1_TP_DOWN,
    IMG_ID_FMRDO_RDS_SKIN_1_TP_DISABLE,
    IMG_ID_FMRDO_RDS_SKIN_1_AF_UP,
    IMG_ID_FMRDO_RDS_SKIN_1_AF_DOWN,
    IMG_ID_FMRDO_RDS_SKIN_1_AF_DISABLE,
    MMI_RP_APP_FMRDO_IMG_MAX
}mmi_rp_app_fmrdo_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_FMRDO_DEF_H */
