/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   mmi_rp_app_soundeffect_def.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Resource populate function generated by XML resgen
 *
 * Author:
 * -------
 *   MTK resgenerator XML parser
 *
 *******************************************************************************/


#ifndef _MMI_RP_APP_SOUNDEFFECT_DEF_H
#define _MMI_RP_APP_SOUNDEFFECT_DEF_H




/******************** Menu resource IDs - begin ********************/
typedef enum
{
    MENU_SETTING_AUDIO_EFFECT = 48185 + 1, /* BASE_ID + 1 */
    MENU_SETTING_SOUND_EFFECT,
    MMI_RP_APP_SOUNDEFFECT_MENU_MAX
}mmi_rp_app_soundeffect_menu_enum;
/******************** Menu resource IDs - finish ********************/


/******************** String resource IDs - begin ********************/
typedef enum
{
    STR_ID_SETTING_SOUND_EFFECT = 48185 + 1, /* BASE_ID + 1 */
    STR_ID_SETTING_AUDIO_EFFECT,
    STR_ID_SETTING_AUDIO_EQUALIZER,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_1,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_2,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_3,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_4,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_5,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_6,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_7,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_8,
    MMI_RP_APP_SOUNDEFFECT_STR_MAX
}mmi_rp_app_soundeffect_str_enum;
/******************** String resource IDs - finish ********************/


/******************** Screen resource IDs - begin ********************/
typedef enum
{
    GRP_ID_SETTING_SOUND_EFFECT = 48185 + 1, /* BASE_ID + 1 */
    SCR_ID_SETTING_SOUND_EFFECT,
    GRP_ID_SETTING_AUDIO_EFFECT,
    SCR_ID_SETTING_AUDIO_EFFECT,
    SCR_ID_SETTING_BASS_ENHANCEMENT,
    SCR_ID_SETTING_AUDIO_EQUALIZER_OPTIONS,
    SCR_ID_SETTING_AUDIO_EQUALIZER_OPTIONS_EDIT,
    SCR_ID_AUDIO_EQUALIZER_SETTING_NAME_EDIT,
    SCR_ID_AUDIO_EQUALIZER_SETTING_NAME_EDIT_OPTION,
    MMI_RP_APP_SOUNDEFFECT_SCR_MAX
}mmi_rp_app_soundeffect_scr_enum;
/******************** Screen resource IDs - finish ********************/
/******************** Template resource IDs - Begin ********************/
/******************** Template resource IDs - End ********************/

/******************** Venus XML resource IDs - Begin ********************/
typedef enum 
{

    MMI_RP_APP_SOUNDEFFECT_VXML_LAYOUT_MAX
} mmi_rp_app_soundeffect_vxml_layout_enum;
/******************** Venus XML resource IDs - End ********************/



/******************** MMI Cache IDs - Begin ********************/
typedef enum
{
    NVRAM_BYTE_AUDIO_REVERB_INDEX = 48185 + 1, /* BASE_ID + 1 */    /*         BYTE */ 
    NVRAM_BYTE_AUDIO_SURROUND_INDEX,                            /*         BYTE */ 
    NVRAM_BYTE_AUDIO_EFFECT_INDEX,                              /*         BYTE */ 
    NVRAM_BYTE_AUDIO_BASS_ENHANCEMENT_INDEX,                    /*         BYTE */ 
    NVRAM_EDITABLE_EQ_RENAME_FLAG,                              /*        SHORT */ 
    MMI_RP_APP_SOUNDEFFECT_MMI_CACHE_MAX
} mmi_rp_app_soundeffect_mmi_cache_enum;
/******************** MMI Cache IDs - End ********************/


/******************** Image resource IDs - begin ********************/
typedef enum
{
    IMG_ID_SETTING_SOUND_EFFECT = 48185 + 1, /* BASE_ID + 1 */
    IMG_ID_SETTING_AUDIO_REVERB_EFFECT,
    MMI_RP_APP_SOUNDEFFECT_IMG_MAX
}mmi_rp_app_soundeffect_img_enum;
/******************** Image resource IDs - finish ********************/


#endif /* _MMI_RP_APP_SOUNDEFFECT_DEF_H */
